# Generated by Django 2.0.5 on 2018-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsupCheckV1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(default='', max_length=36)),
                ('check', models.CharField(choices=[('ac-utf-8-vol-lang.py', 'UTF-8 Security Check'), ('ac-nse-check.py', 'Burt 812801 (NSE)'), ('ac-burt822180.py', 'Burt 822180 (SP)'), ('ac-failed-drives.py', 'Disk Case Failed Drive Counts (ONTAP)'), ('ac-leap2nd-nexus.py', 'Cisco Cluster Interconnect Switch'), ('ac-customer-logs.py', 'Customer Log Counts'), ('ac-drivemine.py', 'Drive Miner'), ('ac-failed-disk-registry.py', 'Failed Disk Registry Analysis'), ('ac-flash-ib.py', 'IB Scrub Flash Details'), ('ac-licensecheck.py', 'License Check'), ('ac-optioncheck.py', 'Option Check'), ('ac-pam-fc-list.py', 'PAM/FC List'), ('ac-section-changes.py', 'Section Changes'), ('ac-section-grep.py', 'Simple ASUP Search'), ('ac-section-to-csv.py', 'Section to CSV'), ('ac-shelf-psus.py', 'Shelf PSU List'), ('ac-aggr-raid.py', 'Shelf Redundancy'), ('ac-snapmirror-status.py', 'SnapMirror Relationships'), ('ac-unowned-disks.py', 'Unowned Disks Report'), ('ac-uptime.py', 'Uptime Report'), ('ac-drive-spare-aggr.py', 'Bank of America Drive Check'), ('ac-xml-section.py', 'XML Section to CSV'), ('ec-health-check.py', 'E-Series Health Check')], max_length=36)),
                ('email', models.CharField(default='', max_length=36)),
                ('verbose', models.BooleanField(default=False)),
                ('options', models.CharField(default='', max_length=36)),
                ('filers', models.TextField(default='#')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
