# Generated by Django 2.0.5 on 2018-05-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('risks_to_highlight', models.TextField()),
                ('hostname_risks_to_highlight', models.TextField()),
                ('repeat_risks_to_highlight', models.TextField()),
                ('risks_to_ack', models.TextField()),
                ('hostname_risks_to_ack', models.TextField()),
                ('risks_to_remove', models.TextField()),
                ('hostname_risks_to_remove', models.TextField()),
                ('risks_to_monitor', models.TextField()),
                ('risk_comments', models.TextField()),
                ('host_risk_comments', models.TextField()),
                ('sites_to_remove', models.TextField()),
                ('hostnames_to_remove', models.TextField()),
                ('input_files', models.FileField(upload_to='')),
                ('output_file', models.FileField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
