# Generated by Django 2.0.5 on 2018-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='host_risk_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hostname_risks_to_ack',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hostname_risks_to_highlight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hostname_risks_to_remove',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hostnames_to_remove',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='input_files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='output_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='repeat_risks_to_highlight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='risk_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='risks_to_ack',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='risks_to_highlight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='risks_to_monitor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='risks_to_remove',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sites_to_remove',
            field=models.TextField(blank=True),
        ),
    ]
