# Generated by Django 2.0.5 on 2018-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0002_auto_20180520_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='input_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
