# Generated by Django 2.0.5 on 2018-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0003_auto_20180520_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
